{% set name = "pycocotools" %}
{% set version = "2.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3829024930013771156521a4b8db4b3aef590556cfa3a8dd3fab027d39b215e1

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv
  skip: true  # [win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - setuptools
    - cython
    - matplotlib-base
    - numpy
  run:
    - python
    - cython
    - matplotlib-base
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - pycocotools
    - pycocotools.mask

about:
  home: https://github.com/cocodataset/cocoapi
  license: BSD-3-Clause
  license_family: BSD
  license_file: license.txt
  summary: Library to work with COCO dataset.
  doc_url: http://cocodataset.org
  dev_url: https://github.com/cocodataset/cocoapi

extra:
  recipe-maintainers:
    - hadim
    - erykoff
